---
- name: Deploy VC and Hosts
  hosts: localhost
  gather_facts: False
  strategy: free
  roles:
    - role: vsphere/vsphere-deploy-vc-and-hosts
    - role: vsphere/vsphere-datacenter
    - role: vsphere/vsphere-clusters
    - role: vsphere/vsphere-vswitch0-port-groups
    - role: vsphere/vsphere-local-datastores
    - role: vsphere/vsphere-enable-cluster-services
    - role: vsphere/vsphere-resource-pools
    - role: vsphere/vsphere-distributed-switches
      when: 'distributed_switches is defined'
    - role: vsphere/vsphere-distributed-port-groups
      when: 'distributed_switches is defined'
    ### vSphere with Kuberentes Section
    - role: vsphere/vsphere-tag-datastore
      when: 'tkgs is defined'
    - role: vsphere/vsphere-content-library
      when: 'tkgs is defined'
    - role: tkgs/tkgs-vyos-router
      when: 'tkgs is defined and tkgs.router is defined'
    - role: tkgs/tkgs-ha-proxy
      when: 'tkgs is defined'
    - role: tkgs/tkgs-enable-cluster
      when: 'tkgs is defined'
    