---
- name: Deploy NSX-T Manager OVA
  community.vmware.vmware_deploy_ovf:
    hostname: "{{ nsxt.hosting_vcenter.ip }}"
    username: "{{ nsxt.hosting_vcenter.username }}" 
    password: "{{ nsxt.hosting_vcenter.password }}" 
    validate_certs: no
    name: "{{ environment_tag }}-{{ item.key }}"
    datacenter: "{{ hosting_vcenter.datacenter }}"
    cluster: "{{ nsxt.manager.hosting_cluster }}"
    datastore: "{{ nsxt.manager.hosting_datastore }}"
    disk_provisioning: "{{ disk_mode }}"
    networks:  
      "VM Network": "{{ nsxt.manager.hosting_network }}"
    ova: "{{ nsxt_ova }}" 
    allow_duplicates: no
    power_on: yes
    fail_on_spec_warnings: yes
    wait: yes
    wait_for_ip_address: yes
    inject_ovf_env: yes
    deployment_option: small
    properties:
      nsx_ip_0: "{{ nsxt.manager.ip }}"
      nsx_netmask_0: "{{ nsxt.manager.netmask }}"
      nsx_gateway_0: "{{ nsxt.manager.gateway }}"
      nsx_dns1_0: "{{ dns1 }}"
      nsx_domain_0: "{{ domain }}"
      nsx_ntp_0: "{{ ntp }}"
      nsx_isSSHEnabled: True
      nsx_allowSSHRootLogin: True
      nsx_hostname: "{{ nsxt.manager.hostname }}"
      nsx_passwd_0: "{{ nsxt.manager.password }}"
      nsx_cli_passwd_0: "{{ nsxt.manager.password }}"
      nsx_cli_audit_passwd_0: "{{ nsxt.manager.password }}"
      nsx_role: "NSX Manager"
  async: 7200
  poll: 0
  register: nsxt_results

- name: Check manager status
  nsxt_manager_status:
    hostname: "{{ nsx.manager_hostname }}"
    username: "{{ nsx.manager_username }}"
    password: "{{ nsx.manager_password }}"
    validate_certs: False
    wait_time: 50

- name: Check all services are up
  uri:
    url: https://{{ nsx.manager.hostname }}/api/v1/cluster-manager/status
    user: "{{ nsx.manager.username }}"
    password: "{{ nsx.manager.password }}"
    method: GET
    force_basic_auth: yes
    validate_certs: False
    return_content: yes
  retries: 60
  delay: 10
  register: result
  until: "'UNKNOWN' not in result.content and 'DOWN' not in result.content"