---
- name: Remove the vCenter VM
  community.vmware.vmware_guest:
    hostname: "{{ hosting_vcenter.ip }}"
    username: "{{ hosting_vcenter.username }}" 
    password: "{{ hosting_vcenter.password }}" 
    validate_certs: no
    name: "{{ environment_tag }}-vcenter"
    state: absent
    force: true
  delegate_to: localhost

- name: Remove ESXi hosts VMs
  community.vmware.vmware_guest:
    hostname: "{{ hosting_vcenter.ip }}"
    username: "{{ hosting_vcenter.username }}" 
    password: "{{ hosting_vcenter.password }}" 
    validate_certs: no
    name: "{{ environment_tag }}-{{ item.key }}"
    state: absent
    force: true
  delegate_to: localhost
  with_dict: "{{ nested_hosts }}"